#!/usr/bin/env python3
"""
生成大量场次 INSERT 语句的脚本
用法示例：
  python scripts\generate_sessions.py --start-date 2025-11-20 --days 7 --per-movie 3 > sql/more_sessions.sql

默认行为：为电影 id 1..16，在 2025-11-20 开始的 7 天内，每天每部电影生成 3 个场次，随机分配到影厅 1..6。
输出：标准输出为 SQL 的 VALUES 列表（包含 INSERT 头），可重定向到文件或追加到现有 seed 文件。
"""
import argparse
import random
from datetime import datetime, timedelta

parser = argparse.ArgumentParser()
parser.add_argument('--start-date', default='2025-11-20', help='起始日期，格式 YYYY-MM-DD')
parser.add_argument('--days', type=int, default=7, help='生成天数')
parser.add_argument('--per-movie', type=int, default=3, help='每部电影每天生成场次数')
parser.add_argument('--movie-ids', default='1-16', help='电影 id 范围或逗号分隔列表，例如 "1-16" 或 "1,2,3"')
parser.add_argument('--halls', default='1-6', help='影厅 id 范围或逗号分隔列表，例如 "1-6" 或 "1,2,3"')
parser.add_argument('--seed', type=int, default=42, help='随机种子（便于重现）')
args = parser.parse_args()

random.seed(args.seed)

# 解析电影 ids
movie_ids = []
if '-' in args.movie_ids:
    a, b = args.movie_ids.split('-', 1)
    movie_ids = list(range(int(a), int(b) + 1))
else:
    movie_ids = [int(x) for x in args.movie_ids.split(',') if x.strip()]

# 解析 halls
halls = []
if '-' in args.halls:
    a, b = args.halls.split('-', 1)
    halls = list(range(int(a), int(b) + 1))
else:
    halls = [int(x) for x in args.halls.split(',') if x.strip()]

# 时间生成辅助
start_date = datetime.strptime(args.start_date, '%Y-%m-%d').date()

# 常用放映时段（小时:minute）池，脚本会随机挑选并加上小幅偏移以避免完全重复
base_times = [ (9,30), (10,0), (11,0), (12,30), (13,0), (14,0), (15,0), (16,30), (17,0), (18,30), (19,0), (20,0), (21,0), (21,30) ]
# 票价区间
price_by_hall = {
    # hall_id: base price
}
for h in halls:
    # base price 35 ~ 70
    price_by_hall[h] = 35 + (h-1)*5

values = []

def format_dt(dt):
    return dt.strftime("%Y-%m-%d %H:%M:%S")

for day_offset in range(args.days):
    day = start_date + timedelta(days=day_offset)
    for movie_id in movie_ids:
        # 选取场次数量
        for s_idx in range(args.per_movie):
            # 随机选择一个放映时段并产生 0/15/30/45 分钟的偏移
            hh, mm = random.choice(base_times)
            mm += random.choice([0, 0, 0, 15, 30])
            # 规范分钟
            extra_hours = mm // 60
            mm = mm % 60
            hh = hh + extra_hours
            start_dt = datetime.combine(day, datetime.min.time()) + timedelta(hours=hh, minutes=mm)
            # 随机片长 90-180 分钟
            duration_min = random.choice([90, 100, 110, 120, 130, 140, 150, 160, 170, 180])
            end_dt = start_dt + timedelta(minutes=duration_min)
            # 随机选择影厅
            hall_id = random.choice(halls)
            # 价格按影厅基价 + movie factor
            price = float(price_by_hall.get(hall_id, 40) + random.choice([0,2,5,0]))
            # 假设可用座位 = capacity - random booked (capacity unknown here; use typical values)
            # 使用 conservative available seats based on hall: small halls (<=40), medium(56~150), large(196)
            capacity_map = {1:120,2:200,3:80,4:40,5:60,6:150}
            capacity = capacity_map.get(hall_id, 100)
            booked = random.randint(0, max(1, capacity//8))
            available = capacity - booked
            # 状态 1（正常）
            status = 1
            values.append("(%d, %d, '%s', '%s', %.2f, %d, %d, %d)" % (
                movie_id, hall_id, format_dt(start_dt), format_dt(end_dt), price, available, booked, status
            ))

# 输出为一个完整的 INSERT 语句（以换行分隔）
if values:
    print("-- Generated by scripts/generate_sessions.py")
    print("INSERT INTO sessions (movie_id, hall_id, start_time, end_time, price, available_seats, booked_seats, status) VALUES")
    for i, v in enumerate(values):
        end = ',' if i < len(values)-1 else ';'
        print('  ' + v + end)
else:
    print('-- no values generated')
